PierresBakery/Models/Flavor.cs
using System.Collections.Generic;

namespace PierresBakery.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int FlavorId { get; set; }
    public string FlavorName { get; set; }

    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }
}

PierresBakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresBakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresBakery.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresBakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresBakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(Flavor => Flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(Flavor => Flavor.FlavorId == id);
      return View(thisFlavor);
    }


    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(Flavor => Flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor Flavor)
    {
      _db.Entry(Flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(Flavor => Flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(Flavor => Flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [HttpPost]
    public async Task<ActionResult> DeleteTreat(int joinId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresBakery/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Add a Treat</h2>

<h4>Add a treat to this flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresBakery/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h4>Add a new flavor</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FlavorName)
  @Html.TextBoxFor(model => model.FlavorName)
  <input type="submit" value="Add a new flavor" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

PierresBakery/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierresBakery/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor;

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor does not contain any treats</p>
}
else
{
  <h4>Treats the flavor contains:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Treat.TreatName</li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Back to flavors", "Index")</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>

PierresBakery/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresBakery.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.FlavorName)
  @Html.EditorFor(model => model.FlavorName)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

PierresBakery/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresBakery.Models;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 

<ul>
  @foreach(Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new flavor", "Create", "Flavors")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>